/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.RiskManagerRole;

import Business.Department.LoanProcessingDepartment;
import Business.Department.RiskAssessmentDepartment;
import Business.Enterprise.Enterprise;
import Business.UserAccount.Useraccount;
import UserInterface.CustomerRole.ApplyLoanJPanel;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author admin01
 */
public class RiskAssessmentWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RiskAssessmentWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private RiskAssessmentDepartment riskAssessmentDepartment;
    private Enterprise enterprise;
    private Useraccount userAccount;
    

    public RiskAssessmentWorkAreaJPanel(JPanel userProcessContainer, Useraccount userAccount, RiskAssessmentDepartment riskAssessmentDepartment, Enterprise enterprise) {
      initComponents();
      this.userProcessContainer=userProcessContainer;
      this.userAccount=userAccount;
      this.riskAssessmentDepartment=(RiskAssessmentDepartment)riskAssessmentDepartment;
      this.enterprise=enterprise;
      lblTime.setText(String.valueOf(new Date()));
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCollateralManagement = new javax.swing.JButton();
        btnApprovedRequests = new javax.swing.JButton();
        btnViewDeclinedRequests = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(5, 37, 69));

        btnCollateralManagement.setBackground(new java.awt.Color(0, 0, 51));
        btnCollateralManagement.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCollateralManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnCollateralManagement.setText("Customer Credit Score Management");
        btnCollateralManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCollateralManagementActionPerformed(evt);
            }
        });

        btnApprovedRequests.setBackground(new java.awt.Color(0, 0, 51));
        btnApprovedRequests.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnApprovedRequests.setForeground(new java.awt.Color(255, 255, 255));
        btnApprovedRequests.setText("View Approved Requests");
        btnApprovedRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprovedRequestsActionPerformed(evt);
            }
        });

        btnViewDeclinedRequests.setBackground(new java.awt.Color(0, 0, 51));
        btnViewDeclinedRequests.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewDeclinedRequests.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDeclinedRequests.setText("View Declined Requets");
        btnViewDeclinedRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDeclinedRequestsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("My Work Area - Customer Service Department");

        lblTime.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login Time:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/RiskManagerRole/images (1).jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnCollateralManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnApprovedRequests)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewDeclinedRequests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCollateralManagement)
                    .addComponent(btnApprovedRequests)
                    .addComponent(btnViewDeclinedRequests))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCollateralManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCollateralManagementActionPerformed
        // TODO add your handling code here:
        CollateralManagementJPanel accountOpeningJPanel = new CollateralManagementJPanel(userProcessContainer, userAccount, riskAssessmentDepartment,  enterprise);
        userProcessContainer.add("manageOrganizationJPanel", accountOpeningJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_btnCollateralManagementActionPerformed

    private void btnApprovedRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprovedRequestsActionPerformed
        // TODO add your handling code here:
        if(riskAssessmentDepartment.getWorkQueue().getWorkRequestList().size()==0){
           JOptionPane.showMessageDialog(null, "You have no approved requests to view !!","Information",JOptionPane.INFORMATION_MESSAGE); 
        }
        else{
        ViewApprovedRequetsJPanel accountOpeningJPanel = new ViewApprovedRequetsJPanel(userProcessContainer, userAccount, riskAssessmentDepartment,  enterprise);
        userProcessContainer.add("manageOrganizationJPanel", accountOpeningJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnApprovedRequestsActionPerformed

    private void btnViewDeclinedRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDeclinedRequestsActionPerformed
        // TODO add your handling code here:
         if(riskAssessmentDepartment.getWorkQueue().getWorkRequestList().size()==0){
           JOptionPane.showMessageDialog(null, "You have no declined requests to view !!","Information",JOptionPane.INFORMATION_MESSAGE); 
        }
        else{
        ViewDeclinedRequestsJPanel accountOpeningJPanel = new ViewDeclinedRequestsJPanel(userProcessContainer, userAccount, riskAssessmentDepartment,  enterprise);
        userProcessContainer.add("manageOrganizationJPanel", accountOpeningJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
         }
    }//GEN-LAST:event_btnViewDeclinedRequestsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprovedRequests;
    private javax.swing.JButton btnCollateralManagement;
    private javax.swing.JButton btnViewDeclinedRequests;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables
}
