/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.Department.Department;
import Business.Department.RiskAssessmentDepartment;
import Business.Enterprise.Enterprise;
import Business.UserAccount.Useraccount;
import Business.Workqueue.RiskAssessmentWorkRequest;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author admin01
 */
public class CollateralDetailJpanel extends javax.swing.JPanel {

    /**
     * Creates new form CollateralDetailJpanel
     */
   

    JPanel userProcessContainer;
    RiskAssessmentWorkRequest request;
    Useraccount account;
    Enterprise enterprise;

    CollateralDetailJpanel(JPanel userProcessContainer,Useraccount account, Enterprise enterprise, RiskAssessmentWorkRequest request) {
        initComponents();
        this.request=(RiskAssessmentWorkRequest)request;
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.enterprise=enterprise;
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtValuation = new javax.swing.JTextField();
        txtInsuranceAmount = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        colltypeComboBox = new javax.swing.JComboBox<>();
        hazardsComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdescription = new javax.swing.JTextArea();
        toDateCombo = new datechooser.beans.DateChooserCombo();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(26, 74, 123));

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Collateral Details:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Type:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Effective Ownership date:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Current date Valuation:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enrironmental Hazards:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Insurance Amount:");

        txtValuation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValuationKeyPressed(evt);
            }
        });

        txtInsuranceAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInsuranceAmountKeyPressed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(1, 25, 50));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        colltypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Real-estate", "Negotiable", "Non-negotiable" }));
        colltypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colltypeComboBoxActionPerformed(evt);
            }
        });

        hazardsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hazards Description:");

        txtdescription.setColumns(20);
        txtdescription.setRows(5);
        txtdescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdescriptionKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtdescription);

        backJButton.setBackground(new java.awt.Color(2, 27, 51));
        backJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnSubmit)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtValuation)
                                .addComponent(txtInsuranceAmount)
                                .addComponent(colltypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hazardsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backJButton)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colltypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValuation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hazardsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInsuranceAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(btnSubmit))
                    .addComponent(toDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(backJButton)
                .addContainerGap(253, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String colltype=(String) colltypeComboBox.getSelectedItem();
        request.setCollateralType(colltype);
        String hazards=(String) hazardsComboBox.getSelectedItem();
        request.setHazard(hazards);
        
        request.setSender(account);
        request.setStatus("Initiated");
        String toDate = toDateCombo.getText();
        
        DateFormat format = new SimpleDateFormat("MM/dd/yy", Locale.ENGLISH);
        Date selectedToDate = null;
        try
        {
            if(txtdescription.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Please enter description","Warning",JOptionPane.WARNING_MESSAGE); 
           return;
            
        }
        else
        {
        request.setHazardDesciption(txtdescription.getText());
        }
            request.setInsuranceAmount(Double.parseDouble(txtInsuranceAmount.getText()));
        request.setValuation(Double.parseDouble(txtValuation.getText()));
        selectedToDate = format.parse(toDate);
        request.setOwnershipDate(selectedToDate);
        Department org = null;
        for (Department department : enterprise.getDepartmentDirectory().getDepartmentList()){
            if (department instanceof RiskAssessmentDepartment){
                org = department;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "Loan details sent successfully","Information",JOptionPane.INFORMATION_MESSAGE);
        }
        }
        catch(Exception e)
        {
            JOptionPane.showConfirmDialog(null, "Please enter valid details !!!","Warning",JOptionPane.WARNING_MESSAGE);
        }

//        Department org = null;
//        for (Department department : enterprise.getDepartmentDirectory().getDepartmentList()){
//            if (department instanceof RiskAssessmentDepartment){
//                org = department;
//                break;
//            }
//        }
//        if (org!=null){
//            org.getWorkQueue().getWorkRequestList().add(request);
//            account.getWorkQueue().getWorkRequestList().add(request);
//            JOptionPane.showMessageDialog(null, "Loan details sent successfully","Information",JOptionPane.INFORMATION_MESSAGE);
//        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void txtValuationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValuationKeyPressed
        // TODO add your handling code here:
        int event =evt.getKeyCode();
        if((event>=evt.VK_0 && event<=evt.VK_9) || event ==evt.VK_BACK_SPACE || (event>=evt.VK_NUMPAD0 && event<=evt.VK_NUMPAD9))
        {
            txtValuation.setEditable(true);
            
        }
        else
        {
            txtValuation.setEditable(false);
            JOptionPane.showMessageDialog(null, "Please enter valid valuation price","Warning",JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_txtValuationKeyPressed

    private void txtInsuranceAmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInsuranceAmountKeyPressed
        // TODO add your handling code here:
        int event =evt.getKeyCode();
        if((event>=evt.VK_0 && event<=evt.VK_9) || event ==evt.VK_BACK_SPACE || (event>=evt.VK_NUMPAD0 && event<=evt.VK_NUMPAD9))
        {
            txtInsuranceAmount.setEditable(true);
            
        }
        else
        {
            txtInsuranceAmount.setEditable(false);
            JOptionPane.showMessageDialog(null, "Please enter valid insurance price","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtInsuranceAmountKeyPressed

    private void txtdescriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescriptionKeyPressed
        // TODO add your handling code here:
        int event =evt.getKeyCode();
        if((event>=evt.VK_A && event<=evt.VK_Z) || event ==evt.VK_BACK_SPACE || event>=evt.VK_CAPS_LOCK || event<=evt.VK_SHIFT )
        {
            txtdescription.setEditable(true);
            
        }
        else
        {
            txtdescription.setEditable(false);
            JOptionPane.showMessageDialog(null, "Please enter valid description","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtdescriptionKeyPressed

    private void colltypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colltypeComboBoxActionPerformed
        // TODO add your handling code here:
         String colltype=(String) colltypeComboBox.getSelectedItem();
         if(colltype.equalsIgnoreCase("Negotiable"))
         {
             hazardsComboBox.setEnabled(false);
             txtdescription.setEnabled(false);
             txtdescription.setText("NA");
         }
         else if(colltype.equalsIgnoreCase("Non-negotiable"))
         {
             hazardsComboBox.setEnabled(false);
             txtdescription.setEnabled(false);
             txtdescription.setText("NA");
             txtInsuranceAmount.setText("0.0");
             txtInsuranceAmount.setEnabled(false);
         }
         else if(colltype.equalsIgnoreCase("Real-Estate"))
         {
             hazardsComboBox.setEnabled(true);
             txtdescription.setEnabled(true);
            // txtdescription.setText("");
             txtInsuranceAmount.setEnabled(true);
             
         }
    }//GEN-LAST:event_colltypeComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> colltypeComboBox;
    private javax.swing.JComboBox<String> hazardsComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private datechooser.beans.DateChooserCombo toDateCombo;
    private javax.swing.JTextField txtInsuranceAmount;
    private javax.swing.JTextField txtValuation;
    private javax.swing.JTextArea txtdescription;
    // End of variables declaration//GEN-END:variables
}
