/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.Useraccount;
import UserInterface.BranchAdminRole.ManageCustomerJPanel;
import UserInterface.BranchAdminRole.ManageDepartmentJPanel;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author admin01
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    Useraccount account;
    public CustomerWorkAreaJPanel(JPanel userProcessContainer,Useraccount account, Enterprise enterprise) { 
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.account=account;
        lblTime.setText(String.valueOf(new Date()));
        lblName.setText("Hello "+ account.getCustomer().getFirstName()+" "+account.getCustomer().getLastName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBanking = new javax.swing.JButton();
        btnBorrowing = new javax.swing.JButton();
        btnAccountServicing = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(43, 77, 145));

        lblName.setBackground(new java.awt.Color(255, 0, 51));
        lblName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(204, 204, 204));

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(204, 204, 204));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Login time:");

        btnBanking.setBackground(new java.awt.Color(4, 39, 75));
        btnBanking.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBanking.setForeground(new java.awt.Color(255, 255, 255));
        btnBanking.setText("Banking");
        btnBanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBankingActionPerformed(evt);
            }
        });

        btnBorrowing.setBackground(new java.awt.Color(1, 25, 49));
        btnBorrowing.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBorrowing.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrowing.setText("Borrowing");
        btnBorrowing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrowingActionPerformed(evt);
            }
        });

        btnAccountServicing.setBackground(new java.awt.Color(1, 25, 49));
        btnAccountServicing.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAccountServicing.setForeground(new java.awt.Color(255, 255, 255));
        btnAccountServicing.setText("Account Servicing");
        btnAccountServicing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountServicingActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(1, 25, 49));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/CustomerRole/finance.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(jLabel2)
                        .addGap(8, 8, 8)
                        .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBanking, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnBorrowing, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnAccountServicing, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBanking)
                    .addComponent(btnBorrowing)
                    .addComponent(btnAccountServicing))
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBankingActionPerformed
        // TODO add your handling code here:
        BankingFunctionalityJPanel manageCustomerJPanel = new BankingFunctionalityJPanel(userProcessContainer, account,enterprise);
        userProcessContainer.add("manageOrganizationJPanel", manageCustomerJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBankingActionPerformed

    private void btnBorrowingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrowingActionPerformed
        // TODO add your handling code here:
        BorrowingFunctionalityJPanel manageCustomerJPanel = new BorrowingFunctionalityJPanel(userProcessContainer, account,enterprise);
        userProcessContainer.add("manageOrganizationJPanel", manageCustomerJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBorrowingActionPerformed

    private void btnAccountServicingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountServicingActionPerformed
        // TODO add your handling code here:
        ViewUpdateContactDetails manageCustomerJPanel = new ViewUpdateContactDetails(userProcessContainer, account,enterprise);
        userProcessContainer.add("manageOrganizationJPanel", manageCustomerJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAccountServicingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccountServicing;
    private javax.swing.JButton btnBanking;
    private javax.swing.JButton btnBorrowing;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables
}
