/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SecurityOperationManagerRole;

import Business.Department.RiskAssessmentDepartment;
import Business.Department.SecurityOperationDepartment;
import Business.Enterprise.Enterprise;
import Business.UserAccount.Useraccount;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author admin01
 */
public class SecurityOperationWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SecurityOperationWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private SecurityOperationDepartment department;
    private Enterprise enterprise;
    private Useraccount userAccount;
    public SecurityOperationWorkAreaJPanel(JPanel userProcessContainer, Useraccount userAccount, SecurityOperationDepartment department, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.department=department;
        this.enterprise=enterprise;
        this.userAccount=userAccount;
        lblTime.setText(String.valueOf(new Date()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInterdepartmentalAlerts = new javax.swing.JButton();
        btnCustomerAlerts = new javax.swing.JButton();
        btnInfoViolationAlerts = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnReport = new javax.swing.JButton();

        setBackground(new java.awt.Color(15, 48, 82));

        btnInterdepartmentalAlerts.setBackground(new java.awt.Color(0, 0, 51));
        btnInterdepartmentalAlerts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInterdepartmentalAlerts.setForeground(new java.awt.Color(255, 255, 255));
        btnInterdepartmentalAlerts.setText("Interdepartmental Alerts");
        btnInterdepartmentalAlerts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterdepartmentalAlertsActionPerformed(evt);
            }
        });

        btnCustomerAlerts.setBackground(new java.awt.Color(0, 0, 51));
        btnCustomerAlerts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCustomerAlerts.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomerAlerts.setText("Employee Session Time Management");
        btnCustomerAlerts.setActionCommand("");
        btnCustomerAlerts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerAlertsActionPerformed(evt);
            }
        });

        btnInfoViolationAlerts.setBackground(new java.awt.Color(0, 0, 51));
        btnInfoViolationAlerts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInfoViolationAlerts.setForeground(new java.awt.Color(255, 255, 255));
        btnInfoViolationAlerts.setText("Information Privacy Violation Alerts");
        btnInfoViolationAlerts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoViolationAlertsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("My Work Area - Security Operation Department");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login Time:");

        lblTime.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SecurityOperationManagerRole/broken_security_lock.jpg"))); // NOI18N

        btnReport.setBackground(new java.awt.Color(0, 0, 51));
        btnReport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReport.setForeground(new java.awt.Color(255, 255, 255));
        btnReport.setText("View violation Reports");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnInterdepartmentalAlerts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCustomerAlerts, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInfoViolationAlerts, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                    .addComponent(btnReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btnReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInterdepartmentalAlerts)
                    .addComponent(btnCustomerAlerts)
                    .addComponent(btnInfoViolationAlerts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInterdepartmentalAlertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterdepartmentalAlertsActionPerformed
        // TODO add your handling code here:
        InterdepartmentalALertsJPanel accountOpeningJPanel = new InterdepartmentalALertsJPanel(userProcessContainer,userAccount,department, enterprise);
        userProcessContainer.add("manageOrganizationJPanel", accountOpeningJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnInterdepartmentalAlertsActionPerformed

    private void btnCustomerAlertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerAlertsActionPerformed
        // TODO add your handling code here:
        CustomerAlertJpanel accountOpeningJPanel = new CustomerAlertJpanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageOrganizationJPanel", accountOpeningJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCustomerAlertsActionPerformed

    private void btnInfoViolationAlertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoViolationAlertsActionPerformed
        // TODO add your handling code here:
        InfoViolationJpanel accountOpeningJPanel = new InfoViolationJpanel(userProcessContainer,userAccount,department, enterprise);
        userProcessContainer.add("manageOrganizationJPanel", accountOpeningJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnInfoViolationAlertsActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        ViewViolationReport accountOpeningJPanel = new ViewViolationReport(userProcessContainer,userAccount,department, enterprise);
        userProcessContainer.add("manageOrganizationJPanel", accountOpeningJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomerAlerts;
    private javax.swing.JButton btnInfoViolationAlerts;
    private javax.swing.JButton btnInterdepartmentalAlerts;
    private javax.swing.JButton btnReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables
}
