/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SecurityOperationManagerRole;

import Business.Department.Department;
import Business.Department.SecurityOperationDepartment;
import Business.Enterprise.Enterprise;
import Business.UserAccount.Useraccount;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.Arrays;
import java.util.Collections;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author admin01
 */
public class ViewViolationReport extends javax.swing.JPanel {

    /**
     * Creates new form ViewViolationReport
     */
    JPanel userProcessContainer;
    Useraccount userAccount;
    SecurityOperationDepartment department;
    Enterprise enterprise;

    ViewViolationReport(JPanel userProcessContainer, Useraccount userAccount, SecurityOperationDepartment department, Enterprise enterprise) {
       initComponents();
       this.userProcessContainer=userProcessContainer;
       this.userAccount=userAccount;
       this.department=department;
       this.enterprise=enterprise;
       for (Department department1 : enterprise.getDepartmentDirectory().getDepartmentList()) {

            organizationEmpJComboBox1.addItem(department1);
        }
    }
    public void viewGraph()
    {
        Department department = (Department) organizationEmpJComboBox1.getSelectedItem();
        int size=department.getEmployeeDirectory().getEmployeeList().size();
        String[] inventory=new String[size];
        for(int i=0;i<size;i++)
        {
           //for(Product p:store.getBranchInventoryCatalog().getBranchInventoryCatalog()) 
           //{
            //if((store.getBranchInventoryCatalog().getBranchInventoryCatalog().get(i).getActualSellingPrice()-store.getBranchInventoryCatalog().getBranchInventoryCatalog().get(i).getCostPrice())>0)
            //{
               inventory[i]=department.getEmployeeDirectory().getEmployeeList().get(i).getViolationCounter()+"-"+department.getEmployeeDirectory().getEmployeeList().get(i).getFirstName();
               System.out.println(inventory[i] + "inventory main");
           // }
           // else
           // {
             // inventory[i]=(0 + "-" +store.getBranchInventoryCatalog().getBranchInventoryCatalog().get(i).getProductName());
           // }
               
           //}
        }
        Arrays.sort(inventory,Collections.reverseOrder());
        DefaultCategoryDataset chart1 = new DefaultCategoryDataset();
        for(int i=0;i<size;i++)
        {
            String[] s1 =inventory[i].split("-");
            chart1.setValue(Double.parseDouble(s1[0]),"Violation Graph",s1[1]);
        }
        JFreeChart barChart1=ChartFactory.createBarChart("Violation Graph", "Violation Graph","No Of violation Attempts", chart1, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot chart5=barChart1.getCategoryPlot();
        chart5.setRangeGridlinePaint(Color.BLUE);
        ChartPanel barPanel=new ChartPanel(barChart1);
        Graph1.removeAll();
        Graph1.add(barPanel, BorderLayout.CENTER);
        Graph1.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        organizationEmpJComboBox1 = new javax.swing.JComboBox();
        Graph1 = new javax.swing.JPanel();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(7, 41, 74));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Department Id:");

        organizationEmpJComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        organizationEmpJComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationEmpJComboBox1ActionPerformed(evt);
            }
        });

        Graph1.setLayout(new java.awt.BorderLayout());

        backJButton.setBackground(new java.awt.Color(2, 27, 51));
        backJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Departmental Violation Report:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(organizationEmpJComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(Graph1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(backJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(organizationEmpJComboBox1))
                .addGap(18, 18, 18)
                .addComponent(Graph1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backJButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void organizationEmpJComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationEmpJComboBox1ActionPerformed
        // TODO add your handling code here:
        //populateRequestTable();
        viewGraph();
    }//GEN-LAST:event_organizationEmpJComboBox1ActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Graph1;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox organizationEmpJComboBox1;
    // End of variables declaration//GEN-END:variables
}
