/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LoanProcessingManagerRole;

import Business.Department.CustomerServiceDepartment;
import Business.Department.LoanProcessingDepartment;
import Business.Enterprise.Enterprise;
import Business.UserAccount.Useraccount;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author admin01
 */
public class LoanProcessingWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoanProcessingWorkAreaJPanel
     */
     private JPanel userProcessContainer;
    private LoanProcessingDepartment department;
    private Enterprise enterprise;
    private Useraccount userAccount;

    public LoanProcessingWorkAreaJPanel(JPanel userProcessContainer, Useraccount userAccount, LoanProcessingDepartment department, Enterprise enterprise) {
       initComponents();
       this.userProcessContainer=userProcessContainer;
       this.userAccount=userAccount;
       this.enterprise=enterprise;
       this.department=(LoanProcessingDepartment)department;
       lblTime.setText(String.valueOf(new Date()));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDisbursementManagement = new javax.swing.JButton();
        btnRepaymentManagement = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(19, 78, 138));

        btnDisbursementManagement.setBackground(new java.awt.Color(11, 11, 73));
        btnDisbursementManagement.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDisbursementManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnDisbursementManagement.setText("Disbursement Management");
        btnDisbursementManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisbursementManagementActionPerformed(evt);
            }
        });

        btnRepaymentManagement.setBackground(new java.awt.Color(11, 11, 73));
        btnRepaymentManagement.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRepaymentManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnRepaymentManagement.setText("Repayment Management");
        btnRepaymentManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepaymentManagementActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("My Work Area - Loan Processing Department");

        lblTime.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login Time:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/LoanProcessingManagerRole/images.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDisbursementManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRepaymentManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisbursementManagement)
                    .addComponent(btnRepaymentManagement))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisbursementManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisbursementManagementActionPerformed
        // TODO add your handling code here:
        DisbursementManagementJPanel accountOpeningJPanel = new DisbursementManagementJPanel(userProcessContainer,userAccount,department, enterprise);
        userProcessContainer.add("manageOrganizationJPanel", accountOpeningJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDisbursementManagementActionPerformed

    private void btnRepaymentManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepaymentManagementActionPerformed
        // TODO add your handling code here:
        RepaymentManagementJPanel accountOpeningJPanel = new RepaymentManagementJPanel(userProcessContainer,userAccount,department, enterprise.getCustomerDirectory());
        userProcessContainer.add("manageOrganizationJPanel", accountOpeningJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRepaymentManagementActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisbursementManagement;
    private javax.swing.JButton btnRepaymentManagement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables
}
