/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HRManager;

import Business.Department.CustomerServiceDepartment;
import Business.Department.Department;
import Business.Department.HRDepartment;
import Business.Department.SecurityOperationDepartment;
import Business.Enterprise.Enterprise;
import Business.UserAccount.Useraccount;
import Business.Workqueue.InfoAlertWorkRequest;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.Arrays;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author admin01
 */
public class ViewEmpReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewEmpReportJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    Useraccount userAccount;
    HRDepartment department;
    ViewEmpReportJPanel(JPanel userProcessContainer,Useraccount userAccount,HRDepartment department, Enterprise enterprise) {
      initComponents();
      this.userProcessContainer=userProcessContainer;
      this.enterprise=enterprise;
      this.userAccount=userAccount;
      this.department=department;
      for (Department department1 : enterprise.getDepartmentDirectory().getDepartmentList()) {

            organizationEmpJComboBox1.addItem(department1);
        }
    }

    
    public void viewGraph()
    {
        Department department = (Department) organizationEmpJComboBox1.getSelectedItem();
        int size=department.getEmployeeDirectory().getEmployeeList().size();
        String[] inventory=new String[size];
        for(int i=0;i<size;i++)
        {
           //for(Product p:store.getBranchInventoryCatalog().getBranchInventoryCatalog()) 
           //{
            //if((store.getBranchInventoryCatalog().getBranchInventoryCatalog().get(i).getActualSellingPrice()-store.getBranchInventoryCatalog().getBranchInventoryCatalog().get(i).getCostPrice())>0)
            //{
               inventory[i]=department.getEmployeeDirectory().getEmployeeList().get(i).getYearlyIncome()+"-"+department.getEmployeeDirectory().getEmployeeList().get(i).getFirstName();
               System.out.println(inventory[i] + "inventory main");
           // }
           // else
           // {
             // inventory[i]=(0 + "-" +store.getBranchInventoryCatalog().getBranchInventoryCatalog().get(i).getProductName());
           // }
               
           //}
        }
        Arrays.sort(inventory,Collections.reverseOrder());
        DefaultCategoryDataset chart1 = new DefaultCategoryDataset();
        for(int i=0;i<size;i++)
        {
            String[] s1 =inventory[i].split("-");
            chart1.setValue(Double.parseDouble(s1[0]),"Salary Graph",s1[1]);
        }
        JFreeChart barChart1=ChartFactory.createBarChart("Salary Graph", "Salary Graph","Values", chart1, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot chart5=barChart1.getCategoryPlot();
        chart5.setRangeGridlinePaint(Color.BLUE);
        ChartPanel barPanel=new ChartPanel(barChart1);
        Graph1.removeAll();
        Graph1.add(barPanel, BorderLayout.CENTER);
        Graph1.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        organizationEmpJComboBox1 = new javax.swing.JComboBox();
        Graph1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnShare = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(101, 111, 117));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Department :");

        organizationEmpJComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        organizationEmpJComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationEmpJComboBox1ActionPerformed(evt);
            }
        });

        Graph1.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(0, 51, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Departmental Salary Dashboard:");

        btnShare.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnShare.setText("Share");
        btnShare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShareActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(2, 27, 51));
        backJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnShare, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(Graph1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(organizationEmpJComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(backJButton)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShare, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(organizationEmpJComboBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Graph1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backJButton)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void organizationEmpJComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationEmpJComboBox1ActionPerformed
        // TODO add your handling code here:
        //populateRequestTable();
        viewGraph();

    }//GEN-LAST:event_organizationEmpJComboBox1ActionPerformed

    private void btnShareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShareActionPerformed
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(null, "Information privacy violation alert will be sent to security department.Do you want to continue sending?", "Security Alert", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            InfoAlertWorkRequest request=new InfoAlertWorkRequest();
            request.setSender(userAccount);
            request.setContent("Salary Report");
            userAccount.getEmployee().incrementCounter();
            
        //request.setMessage(message);
        
        request.setStatus("Sent");
        
        Department org = null;
        for (Department department : enterprise.getDepartmentDirectory().getDepartmentList()){
            if (department instanceof SecurityOperationDepartment){
                org = department;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "Alert sent to security department!!","Warning",JOptionPane.WARNING_MESSAGE);
        }
        }
        else {
           JOptionPane.showMessageDialog(null, "Thank you for security awareness!!");
           return;
           //System.exit(0);
        }
        
    }//GEN-LAST:event_btnShareActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Graph1;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnShare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox organizationEmpJComboBox1;
    // End of variables declaration//GEN-END:variables
}
