/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HRManager;

import Business.Department.Department;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Loan.Loan;
import Business.Network.Customer;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin01
 */
public class ViewDeptEmpDirectoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDeptEmpDirectoryJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;

    ViewDeptEmpDirectoryJPanel(JPanel userProcessContainer, Enterprise enterprise) {
       initComponents(); 
       this.userProcessContainer=userProcessContainer;
       this.enterprise=enterprise;
       for (Department department : enterprise.getDepartmentDirectory().getDepartmentList()) {

            organizationEmpJComboBox1.addItem(department);
        }
    }
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) tblEmployee.getModel();
        Department department = (Department) organizationEmpJComboBox1.getSelectedItem();
        model.setRowCount(0);
        //for()
        for (Employee employee : department.getEmployeeDirectory().getEmployeeList()){
            Object[] row = new Object[5];
            row[0] = employee;
            row[1] = employee.getFirstName();
            row[2] = employee.getLastName();
            row[3] = employee.getPhNo();
            row[4] = employee.getSSN();
            
            
            
            
            model.addRow(row);
        }
    }
    public void refreshProductTable(int key)
     {
         DefaultTableModel dtm=(DefaultTableModel) tblEmployee.getModel();
         Department department = (Department) organizationEmpJComboBox1.getSelectedItem();
         dtm.setRowCount(0);
         for(Employee employee : department.getEmployeeDirectory().getEmployeeList())
         {
             
                 if(key==employee.getEmployeeId())
                 {
                 Object row[]=new Object[5];
                 row[0] = employee;
            row[1] = employee.getFirstName();
            row[2] = employee.getLastName();
            row[3] = employee.getPhNo();
            row[4] = employee.getSSN();
            
               dtm.addRow(row);
                 
                     }
             
         }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearchPerson = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnViewProfile = new javax.swing.JButton();
        txtKey = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        organizationEmpJComboBox1 = new javax.swing.JComboBox();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 102));

        btnSearchPerson.setBackground(new java.awt.Color(0, 0, 0));
        btnSearchPerson.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchPerson.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchPerson.setText("Search Profile");
        btnSearchPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPersonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Employee Directory:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Emp Id:");

        btnViewProfile.setBackground(new java.awt.Color(0, 0, 0));
        btnViewProfile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnViewProfile.setText("View Profile");
        btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfileActionPerformed(evt);
            }
        });

        txtKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeyActionPerformed(evt);
            }
        });

        tblEmployee.setBackground(new java.awt.Color(0, 0, 0));
        tblEmployee.setForeground(new java.awt.Color(255, 255, 255));
        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmpID", "First Name", "Last Name", "Ph No", "SSN"
            }
        ));
        jScrollPane2.setViewportView(tblEmployee);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Department Id:");

        organizationEmpJComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        organizationEmpJComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationEmpJComboBox1ActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(2, 27, 51));
        backJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backJButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(organizationEmpJComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(btnSearchPerson)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(424, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organizationEmpJComboBox1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchPerson))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewProfile)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(backJButton)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPersonActionPerformed
        // TODO add your handling code here:
        if(txtKey.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter personID !","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {

            try
            {
                int key= Integer.parseInt(txtKey.getText());
                refreshProductTable(key);

//                Person result=personHistory.searchPerson(key);
//                if (result != null) {
//                    ViewProfileJPanel panel =new ViewProfileJPanel(result, userProcessContainer);
//                    // SearchProfileJPanel panel = new SearchProfileJPanel(userProcessContainer, result);
//                    userProcessContainer.add("SearchProfileJPanel", panel);
//                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//                    layout.next(userProcessContainer);
//                } else {
//                    JOptionPane.showMessageDialog(null, "Person ID to search dosen't exist in the records.", "Information", JOptionPane.INFORMATION_MESSAGE);
//                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Please enter valid value for personID","Warning",JOptionPane.WARNING_MESSAGE);
            }
        }
        

    }//GEN-LAST:event_btnSearchPersonActionPerformed

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
//        // TODO add your handling code here:
        int selectedRow= tblEmployee.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first to view detail", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            Employee employee=(Employee)tblEmployee.getValueAt(selectedRow, 0);
            ViewProfileJPanel panel = new ViewProfileJPanel(employee,userProcessContainer);
            userProcessContainer.add("ViewProfileJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnViewProfileActionPerformed

    private void txtKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeyActionPerformed

    private void organizationEmpJComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationEmpJComboBox1ActionPerformed
        // TODO add your handling code here:
        populateRequestTable();
        
    }//GEN-LAST:event_organizationEmpJComboBox1ActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnSearchPerson;
    private javax.swing.JButton btnViewProfile;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox organizationEmpJComboBox1;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTextField txtKey;
    // End of variables declaration//GEN-END:variables
}
